# Generated by Django 5.0.4 on 2024-07-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_firstname', models.CharField(blank=True, max_length=80, null=True)),
                ('user_lastname', models.CharField(blank=True, max_length=80, null=True)),
                ('user_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('user_adate', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_status', models.CharField(blank=True, default='AC', max_length=4, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('user_desg', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
