# Generated by Django 5.0.4 on 2024-07-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_fcm_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
