# Generated by Django 5.0.4 on 2024-07-01 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleOptionCategory',
            fields=[
                ('copc_id', models.AutoField(primary_key=True, serialize=False)),
                ('copc_code', models.CharField(max_length=30, unique=True)),
                ('copc_name', models.CharField(max_length=30)),
                ('copc_status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Inactive')], default='AC', max_length=2)),
                ('copc_category', models.CharField(max_length=255)),
                ('copc_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.consoleoptioncategory')),
            ],
            options={
                'db_table': 'console_option_categories',
            },
        ),
        migrations.CreateModel(
            name='ConsoleOption',
            fields=[
                ('copt_id', models.AutoField(primary_key=True, serialize=False)),
                ('copt_code', models.CharField(max_length=50, unique=True)),
                ('copt_name', models.CharField(max_length=50)),
                ('copt_status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Inactive')], default='AC', max_length=2)),
                ('copt_category', models.CharField(blank=True, default='ADMN', max_length=10, null=True)),
                ('copt_copc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.consoleoptioncategory')),
            ],
            options={
                'db_table': 'console_options',
            },
        ),
        migrations.CreateModel(
            name='UserConsoleOptions',
            fields=[
                ('usco_id', models.AutoField(primary_key=True, serialize=False)),
                ('usco_copt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.consoleoption')),
                ('usco_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_console_options',
            },
        ),
    ]
