# Generated by Django 5.0.4 on 2025-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('appi_id', models.AutoField(primary_key=True, serialize=False)),
                ('appi_idate', models.DateTimeField(auto_now_add=True)),
                ('appi_catg', models.CharField(blank=True, max_length=100, null=True)),
                ('appi_uniqid', models.CharField(max_length=255, unique=True)),
                ('appi_device_act', models.CharField(blank=True, max_length=255, null=True)),
                ('appi_appversion', models.CharField(blank=True, max_length=50, null=True)),
                ('appi_devicetype', models.CharField(blank=True, max_length=100, null=True)),
                ('appi_devicemodel', models.CharField(blank=True, max_length=100, null=True)),
                ('appi_devicemake', models.CharField(blank=True, max_length=100, null=True)),
                ('appi_deviceos', models.CharField(blank=True, max_length=50, null=True)),
                ('appi_deviceosversion', models.CharField(blank=True, max_length=50, null=True)),
                ('appi_pntoken', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'app_installations',
            },
        ),
    ]
