# Generated by Django 5.0.4 on 2025-05-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterentry', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('torp_id', models.AutoField(primary_key=True, serialize=False)),
                ('torp_name', models.CharField(max_length=200)),
                ('torp_description', models.TextField(blank=True, null=True)),
                ('torp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('torp_package_type', models.CharField(choices=[('DIRECT', 'Direct Package'), ('ITINERARY', 'Itinerary Package')], default='DIRECT', max_length=10)),
                ('torp_duration', models.PositiveIntegerField()),
                ('torp_start_date', models.DateField(blank=True, null=True)),
                ('torp_end_date', models.DateField(blank=True, null=True)),
                ('torp_inclusions', models.TextField(blank=True, null=True)),
                ('torp_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_packages', to='masterentry.destination')),
                ('torp_end_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_packages', to='masterentry.destination')),
                ('torp_start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_packages', to='masterentry.destination')),
            ],
            options={
                'db_table': 'tour_packages',
            },
        ),
        migrations.CreateModel(
            name='TourPackageItinerary',
            fields=[
                ('itnr_id', models.AutoField(primary_key=True, serialize=False)),
                ('itnr_day_number', models.PositiveIntegerField()),
                ('itnr_date', models.DateField()),
                ('itnr_activities', models.TextField(blank=True, null=True)),
                ('itnr_location', models.CharField(blank=True, max_length=100, null=True)),
                ('itnr_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_packages.tourpackage')),
            ],
            options={
                'db_table': 'tour_package_itineraries',
            },
        ),
    ]
