# Generated by Django 5.0.4 on 2025-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_packages', '0002_tourpackage_torp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='torp_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
