# Generated by Django 5.0.4 on 2025-04-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('doct_id', models.AutoField(primary_key=True, serialize=False)),
                ('doct_name', models.CharField(max_length=50, unique=True)),
                ('doct_code', models.CharField(max_length=50, unique=True)),
                ('doct_ludate', models.DateTimeField(auto_now=True)),
                ('doct_status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2)),
            ],
            options={
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='GuideTypes',
            fields=[
                ('gudt_id', models.AutoField(primary_key=True, serialize=False)),
                ('gudt_name', models.CharField(max_length=50, unique=True)),
                ('gudt_code', models.CharField(max_length=50, unique=True)),
                ('gudt_ludate', models.DateTimeField(auto_now=True)),
                ('gudt_status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2)),
            ],
            options={
                'db_table': 'guide_types',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=50, unique=True)),
                ('lang_ludate', models.DateTimeField(auto_now=True)),
                ('lang_status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skil_id', models.AutoField(primary_key=True, serialize=False)),
                ('skil_name', models.CharField(max_length=50, unique=True)),
                ('skil_ludate', models.DateTimeField(auto_now=True)),
                ('skil_status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
