# Generated by Django 5.0.4 on 2025-05-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterentry', '0002_destination'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destination',
            table='destinations',
        ),
    ]
