# Generated by Django 5.0.4 on 2025-04-15 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('gude_id', models.AutoField(primary_key=True, serialize=False)),
                ('gude_full_name', models.CharField(max_length=100)),
                ('gude_age', models.IntegerField()),
                ('gude_email', models.CharField(max_length=255, unique=True)),
                ('gude_mobile', models.CharField(max_length=10, unique=True)),
                ('gude_password_hash', models.CharField(max_length=255)),
                ('gude_profile_image', models.CharField(max_length=255)),
                ('gude_has_car', models.CharField(default='NA', max_length=2)),
                ('gude_experiance', models.IntegerField()),
                ('gude_is_verified', models.CharField(default='YTA', max_length=3)),
                ('gude_fcm_token', models.CharField(max_length=500)),
                ('gude_created_at', models.DateTimeField(auto_now_add=True)),
                ('gude_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterentry.guidetypes')),
            ],
            options={
                'db_table': 'guides',
            },
        ),
        migrations.CreateModel(
            name='GuideLanguages',
            fields=[
                ('gdln_id', models.AutoField(primary_key=True, serialize=False)),
                ('gdln_lang', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterentry.languages')),
                ('gdln_gude', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guides.guides')),
            ],
            options={
                'db_table': 'guide_languages',
                'unique_together': {('gdln_gude', 'gdln_lang')},
            },
        ),
        migrations.CreateModel(
            name='GuideDocuments',
            fields=[
                ('gddc_id', models.AutoField(primary_key=True, serialize=False)),
                ('gddc_doc_file', models.CharField(max_length=255)),
                ('Equipmentgddc_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gddc_status', models.CharField(default='AC', max_length=4)),
                ('gddc_doct', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterentry.documenttypes')),
                ('gddc_gude', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guides.guides')),
            ],
            options={
                'db_table': 'guide_documents',
                'unique_together': {('gddc_gude', 'gddc_doct')},
            },
        ),
        migrations.CreateModel(
            name='GuideSkills',
            fields=[
                ('gdsk_id', models.AutoField(primary_key=True, serialize=False)),
                ('gdsk_gude', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guides.guides')),
                ('gdsk_skill', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='masterentry.skills')),
            ],
            options={
                'db_table': 'guide_skills',
                'unique_together': {('gdsk_gude', 'gdsk_skill')},
            },
        ),
    ]
