# Generated by Django 5.0.4 on 2025-03-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerusers',
            fields=[
                ('cusr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cusr_full_name', models.CharField(max_length=100, null=True)),
                ('cusr_age', models.IntegerField(blank=True, null=True)),
                ('cusr_email', models.CharField(max_length=255, unique=True)),
                ('cusr_password_hash', models.CharField(max_length=255)),
                ('cusr_profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('cusr_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('cusr_is_verified', models.CharField(default='N', max_length=1)),
                ('cusr_created_at', models.DateTimeField(auto_now_add=True)),
                ('cusr_fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('cusr_last_login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('cusr_status', models.CharField(default='AC', max_length=2)),
                ('cust_otp', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'customers_users',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customerusers')),
            ],
            options={
                'db_table': 'user_otps',
            },
        ),
    ]
